// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Siemens.DotNetCore.PmsApp.Repository;

#nullable disable

namespace Siemens.DotNetCore.PmsApp.Repository.Migrations
{
    [DbContext(typeof(SiemensDbContext))]
    [Migration("20251128083111_InitialDbSetUp")]
    partial class InitialDbSetUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Siemens.DotNetCore.PmsApp.Repository.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productname");

                    b.HasKey("ProductId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "A high-performance laptop.",
                            Price = 1200.00m,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "A latest model smartphone.",
                            Price = 800.00m,
                            ProductName = "Smartphone"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "A lightweight tablet.",
                            Price = 500.00m,
                            ProductName = "Tablet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
