// <auto-generated />
using EFCoreDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDemo.Migrations
{
    [DbContext(typeof(SiemensDbContext))]
    partial class SiemensDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreDemo.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("deptid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("deptname");

                    b.HasKey("DeptId")
                        .HasName("pk_departments_deptid");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "Human Resources"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "Information Technology"
                        });
                });

            modelBuilder.Entity("EFCoreDemo.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("empid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("deptid");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("empname");

                    b.Property<decimal?>("Salary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("salary");

                    b.HasKey("EmpId")
                        .HasName("pk_employees_empid");

                    b.HasIndex("DeptId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmpId = 1,
                            DeptId = 1,
                            EmpName = "John Doe",
                            Salary = 60000.00m
                        },
                        new
                        {
                            EmpId = 2,
                            DeptId = 2,
                            EmpName = "Jane Smith",
                            Salary = 75000.00m
                        });
                });

            modelBuilder.Entity("EFCoreDemo.Employee", b =>
                {
                    b.HasOne("EFCoreDemo.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Employee_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCoreDemo.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
